#!/bin/bash

transmission_storage()
{
	if ! xbian-storager listvol | grep -qw storage$; then
		xbian-storager createvol --mount $@ --name='xbian-package-transmission' storage /home/xbian/storage
		chown -R xbian:xbian /home/xbian/storage
	fi

	mountpoint -q /home/xbian/storage || mount /home/xbian/storage 2>/dev/null

	if [ ! -d /home/xbian/storage/transmission/downloads ] || [ ! -d /home/xbian/storage/transmission/incomplete ]; then
		mkdir -p /home/xbian/storage/transmission/downloads
		chattr +C /home/xbian/storage/transmission/downloads 2>/dev/null || :

		mkdir -p /home/xbian/storage/transmission/incomplete
		chattr +C /home/xbian/storage/transmission/incomplete 2>/dev/null || :

		chown -R xbian:xbian /home/xbian/storage/transmission
	fi
}

if [ "$1" = configure ]; then
	
	/etc/init.d/transmission-daemon stop &>/dev/null
	stop transmission-daemon &>/dev/null

	chmod 664 /etc/default/transmission-daemon
	chgrp xbian /etc/default/transmission-daemon

	update-rc.d transmission-daemon remove &>/dev/null

	transmission_storage --exclude

	if [ ! -d /home/xbian/downloads ]; then
		if pgrep "xbmc.bin|kodi.bin" >/dev/null; then
			MSGPATHV='/run/splash'
			HOSTNAME=$(hostname)
			su -c "echo -e \"Transmission\nTransmission's WebGUI is accessable under address\nhttp://localhost:9091 or http://$HOSTNAME:9091\nusername: xbian, password raspberry\n\$\" >> $MSGPATHV/msg4kodi" xbian || :
		else
			echo "************************************************"
			echo "***              Transmission                ***"
			echo "***       You can access WebGUI under        ***"
			echo "***    http://localhost:9091, user xbian,    ***"
			echo "***          password raspberry              ***"
			echo "************************************************" 
		fi
	fi

	if [ -d /home/xbian/downloads -a ! -h /home/xbian/downloads ]; then
		echo "Moving Transmission's downloads folder to storage subvolume ... "
		find /home/xbian/downloads/ -maxdepth 1 -mindepth 1 -exec mv -f {} /home/xbian/storage/transmission/downloads/ \; -exec rm -rf {} \;
		rmdir /home/xbian/downloads
	fi

	if [ -d /home/xbian/incomplete -a ! -h /home/xbian/incomplete ]; then
		echo "Moving Transmission's incomplete folder to storage subvolume ... "
		find /home/xbian/incomplete/ -maxdepth 1 -mindepth 1 -exec mv -f {} /home/xbian/storage/transmission/incomplete/ \; -exec rm -rf {} \;
		rmdir /home/xbian/incomplete
	fi

	chown -R xbian:xbian /home/xbian/storage/transmission

	[ -d /home/xbian/downloads ] || ln -s storage/transmission/downloads/ /home/xbian/downloads
	chown -R xbian:xbian /home/xbian/downloads

	[ -d /home/xbian/incomplete ] || ln -s storage/transmission/incomplete/ /home/xbian/incomplete
	chown -R xbian:xbian /home/xbian/incomplete

	mkdir -p /home/xbian/torrents
	chown -R xbian:xbian /home/xbian/torrents

	if [ -d /etc/transmission -a ! -h /etc/transmission ]; then
	    cp -a /etc/transmission /home/xbian
	    rm -rf /etc/transmission
	    ln -s  ../home/xbian/transmission /etc/transmission
	fi
	[ -e /tmp/settings.json ] && mv /tmp/settings.json /home/xbian/transmission

	if grep -qs "ENABLED=0" /etc/default/transmission; then
		sed -i "s/ENABLE_DAEMON=.*/ENABLE_DAEMON=0/g" /etc/default/transmission-daemon
	fi
	rm -f /etc/default/transmission

	if [ ! -h /etc/transmission-daemon ]; then
		rm -rf /etc/transmission-daemon
		ln -s ../home/xbian/transmission /etc/transmission-daemon
	fi

	chown -R xbian:xbian /home/xbian/transmission

	xbian-config services insert transmission-daemon &>/dev/null
	xbian-config services start transmission-daemon &>/dev/null || :
fi
