#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if [ -f "/etc/init.d/transmission" ]; then
                /etc/init.d/transmission stop &>/dev/null
                update-rc.d transmission remove &>/dev/null
        fi

        if [ -f "/etc/init.d/transmission-daemon" ]; then
                /etc/init.d/transmission-daemon stop &>/dev/null
        fi

        stop transmission-daemon &>/dev/null

	xbian-config services delete transmission &>/dev/null

        if [ -d "/usr/local/etc/transmission/" ]; then
		mv /usr/local/etc/transmission /home/xbian/
		ln -s /home/xbian/transmission /usr/local/etc/transmission
	fi

fi

exit 0
