#!/bin/bash

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then

        if [ -f "/etc/init.d/transmission" ]; then
                /etc/init.d/transmission stop &>/dev/null;
        fi

        if [ -f "/etc/init.d/transmission-daemon" ]; then
                /etc/init.d/transmission-daemon stop &>/dev/null;
        fi

	stop transmission-daemon &>/dev/null

	xbian-config services delete transmission-daemon &>/dev/null

fi

exit 0
