#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if [ -f "/etc/init.d/transmission" ]; then
                /etc/init.d/transmission stop &>/dev/null;
        fi

        if [ -d "/usr/local/etc/transmission/" ]; then

		mv /usr/local/etc/transmission /etc/transmission
		
		ln -s /etc/transmission /usr/local/etc/transmission
		
	else
		true
	fi

fi
